title: SAIGRC Blog
description: Insights and updates on healthcare AI governance, risk management, and compliance
baseurl: "/Saigrc"
url: "https://systems-for-ai-governance.github.io"

# Blog settings
permalink: /blog.html/:year/:month/:day/:title/

# Build settings
markdown: kramdown
theme: jekyll-theme-primer 